-- Tabela: produtos
CREATE TABLE public.produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    descricao TEXT,
    preco NUMERIC(10,2) NOT NULL,
    categoria TEXT NOT NULL,
    ativo BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela: motoboys
CREATE TABLE public.motoboys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    telefone TEXT,
    placa_moto TEXT,
    ativo BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela: entregas
CREATE TABLE public.entregas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_nome TEXT NOT NULL,
    endereco TEXT NOT NULL,
    valor_entrega NUMERIC(10,2) NOT NULL DEFAULT 0,
    data_entrega DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'pendente', -- pendente, em_transito, entregue, cancelado
    motoboy_id BIGINT REFERENCES public.motoboys(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela: caixa
CREATE TABLE public.caixa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_abertura TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    data_fechamento TIMESTAMP WITH TIME ZONE,
    valor_inicial NUMERIC(10,2) NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'aberto' -- aberto, fechado
);

-- Tabela: movimentacoes_caixa
CREATE TABLE public.movimentacoes_caixa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caixa_id BIGINT NOT NULL REFERENCES public.caixa(id) ON DELETE CASCADE,
    tipo TEXT NOT NULL, -- entrada, saida
    valor NUMERIC(10,2) NOT NULL,
    descricao TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS em todas as tabelas
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.motoboys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entregas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.caixa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimentacoes_caixa ENABLE ROW LEVEL SECURITY;